### PR TITLE
Add Summer 2017 iPads

### PR DESCRIPTION
**Pull request by SlaunchaMan**
This PR adds the 10.5" iPad Pro and the 12.9" iPad Pro (2nd Generation).

### CODE REVIEW

**Comment by SlaunchaMan** [comment]
@sebyddd Can we get this merged in?

**Comment by sebyddd** [comment]
Works great! Merged it.

**Comment by SlaunchaMan** [comment]
Awesome, thanks! (And don’t forget a CocoaPods release!)

**Comment by sebyddd** [comment]
@SlaunchaMan – Done. CocoaPods v4.1

**Comment by SlaunchaMan** [comment]
💯

**Pull request merged**
