### PR TITLE
[WIP] OSX compatibility

### PR DESCRIPTION
**Pull request by tbaranes**
That really not finish, but just a first implementation about it. Before going further, I prefer discuss the implementation with you. This PR contains just the basic to have the mac information by just copying your structure and adapt it to OSX. I didn't fill each device model information, but let links to apple documentation about it.

That can work, but it's not pretty useful in order to handle and maintain both platforms. A better way would be to have an abstract the implementation, adapt it for each platforms, but the usage will be transparent whatever is the device. We can keep the same enums name, the same methods name (maybe add one or two following the case). 

Also, do we really want all the information about the mac: model, inch, retina, release year...? Once we have one, it's easy to have the others, so I don't think that will add a lot of work once we did it for the existing ones.

Beside the architecture / implementation to do, an update of the README and the pod spec will be mandatory.

Issue #20

### CODE REVIEW

**Comment by sebyddd** [comment]
Awesome additions, Tom! 
I agree with you on the architecture changes. 

The way I think of this library as a next big update is this: Rename the library to SDVersion. Have a main SDVersion class and 2 other classes: SDiPhoneVersion and SDMacVersion (those will be imported in  the SDVersion class). 
This will keep the 2 platforms on separate tracks and the code cleaner. 

As for the information we need on the Mac side: I think that: Model, Year, Inch, Retina and Resolution (pixel size) are the most useful ones to have. 

The goal is to keep the library compact & easy to use. If you could modify the PR to include the new SDMacVersion class on the main SDiPhoneVersion folder it would be great. I will take care of the renaming and the demo project and will also make sure to mention you for the help on this new version. 

Cheers!

P.S: Do you have Skype? Contact me through my email listed on the profile, so we can chat more about it. :smile:

**Comment by tbaranes** [comment]
And this it! New project architecture, so now we have:
- A header file `SDVersion.h` which will include `SDiPhoneVersion` or `SDMacVersion` following the platform detected
- Two classes: `SDiPhoneVersion` and `SDMacVersion` which are transparent for the user

I also updated the demo project to compile on each platform following that architecture. The usage is really simple, we just have:

```
#import "SDVersion.h"
[SDVersion deviceName];
```

**Comment by tbaranes** [comment]
Architecture updated :)

**Comment by sebyddd** [comment]
Thanks for the contribution Tom!

Just posted version 2.1 of SDVersion. (26ae5f8f6413cd98f77adf08f703390d62067f6a)
I mentioned you in the README. 

Cheers!

**Comment by tbaranes** [comment]
Awesome, thanks to you! :+1:

**Pull request closed without merging**
