### PR TITLE
replace like "stringFromDeviceVersion(v)" with "static NSString *Devi…

### PR DESCRIPTION
**Pull request by sinofake**
…ceVersionNames[]"

### CODE REVIEW

**Comment by sinofake** [comment]
modify README.md

**Comment by sebyddd** [comment]
Looks great. :+1: 
Can you please run the demo project in Xcode 7 and upgrade the project to the latest SDK?

**Comment by sinofake** [comment]
@sebyddd  I've run the demo project in Xcode 7.0.1, everything is normal

**Comment by kevindelord** [comment]
@sebyddd will you merge this pull request? it looks great !

**Comment by sebyddd** [comment]
Yep. It looks good indeed!

**Pull request merged**
